package com.wx.exam1.domain;


import java.util.Date;
import java.util.List;

public class Country {

    private List<City> cities;

    public List<City> getCities() {
        return cities;
    }

    public void setCities(List<City> cities) {
        this.cities = cities;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.country_id
     *
     * @mbggenerated
     */
    private Short country_id;

    public Short getCountry_id() {
        return country_id;
    }

    public void setCountry_id(Short country_id) {
        this.country_id = country_id;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.last_update
     *
     * @mbggenerated
     */
    private Date lastUpdate;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.country_id
     *
     * @return the value of country.country_id
     * @mbggenerated
     */


    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.last_update
     *
     * @return the value of country.last_update
     * @mbggenerated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.last_update
     *
     * @param lastUpdate the value for country.last_update
     * @mbggenerated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}